services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      - TZ=${TZ:-UTC}
      - SERVER_ADMIN=${SERVER_ADMIN:-you@example.com}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-8M}
    volumes:
      - linkstack_data:/htdocs
    ports:
      - 8443:443 
    restart: unless-stopped
    networks:
      - coolify 
   
volumes:
  linkstack_data:
