version: "3.8"

services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      - TZ=${TZ:-UTC}
      - SERVER_ADMIN=${SERVER_ADMIN:-you@example.com}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-8M}
    volumes:
      - linkstack_data:/htdocs
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkstack.rule=Host(`link.app.covadigital.io`)
      - traefik.http.routers.linkstack.entrypoints=websecure
      - traefik.http.routers.linkstack.tls=true
      - traefik.http.routers.linkstack.tls.certresolver=letsencrypt
      - traefik.http.services.linkstack.loadbalancer.server.port=443

volumes:
  linkstack_data:

networks:
  coolify:
    external: true
